In [1]:
#1
name="jai"
age=22
print(name)
print(age)

jai
22


In [2]:
#2
X="Datascience is used to extract meaningful insights."
x=X.split(" ")
x

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [3]:
#3
def mul(a,b):
    c=a*b
    print(c)
mul(3,4)

12


In [4]:
#4
states={"UP":"lucknow","Punjab":"chandigarh","HP":"shimla","MP":"bhopal","Haryana":"gurgaon"}
print("Keys:", list(states.keys()))
print("Values:", list(states.values()))

Keys: ['UP', 'Punjab', 'HP', 'MP', 'Haryana']
Values: ['lucknow', 'chandigarh', 'shimla', 'bhopal', 'gurgaon']


In [5]:
#5
numbers = list(range(1, 1000))

In [6]:
#6
import numpy as np
identity_matrix = np.identity(4)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#7
matrix_3x3 = np.arange(1, 10).reshape(3, 3)
print("3x3 matrix:")
print(matrix_3x3)

3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#8
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
sum_array = array1 + array2
print("Sum of arrays:")
print(sum_array)

Sum of arrays:
[[ 6  8]
 [10 12]]


In [9]:
#9
import pandas as pd
from datetime import datetime
start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)
dates = pd.date_range(start_date, end_date, freq='D')
print("Series of dates:")
print(dates)

Series of dates:
DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [10]:
#10
data = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

DataFrame:
     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
