In [1]:
##Assignment -1 
## Applied Data Science



In [21]:
import numpy as np
import pandas as pd 
from datetime import datetime, timedelta

In [22]:
## Q1. Assign your Name to variable name and Age to variable age. Make a Python program that 
## prints your name and age.

name="Syed Qasim Kaif"
age=20;
print(name)
print(age)

Syed Qasim Kaif
20


In [23]:
##Q2.X="Datascience is used to extract meaningful insights."
## Split the string
X="Datascience is used to extract meaningful insights."
X.split()


['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [24]:
##Q3. Make a function that gives multiplication of two numbers

def multiply_numbers(n1, n2):
    mult = n1 * n2
    return mult
mult=multiply_numbers(1,3)
print(mult)


3


In [25]:
## Q4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

# Creating a dictionary of states and capitals
statescapitals = {
    'Maharastra': 'Mumbai',
    'Gujarat': 'Gandhinagar',
    'Telengana': 'Hyderabad',
    'Tamil Nadu': 'Chennai',
    'Karnataka': 'Bengaluru'
}
for state in statescapitals.keys():
    print(state)
for capital in statescapitals.values():
    print(capital)


Maharastra
Gujarat
Telengana
Tamil Nadu
Karnataka
Mumbai
Gandhinagar
Hyderabad
Chennai
Bengaluru


In [26]:
##Q5.Create a list of 1000 numbers using range function.
l=[]
for i in range(1,10001):
    l.append(i)


In [27]:
##Q6.Create an identity matrix of dimension 4 by 4

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
##Q7. Create a 3x3 matrix with values ranging from 1 to 9
array_1dim = np.arange(1, 10)
matrix_3x3 = np.reshape(array_1dim, (3, 3))
print(matrix_3x3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
##Q8. Create 2 similar dimensional array and perform sum on them
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])
result = array1 + array2
print(result)


[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [31]:
##Q9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)
start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

dates = []
current_date = start_date

while current_date <= end_date:
    dates.append(current_date.strftime('%d-%m-%Y'))
    current_date += timedelta(days=1)

print(dates)


['01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023', '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023', '10-02-2023', '11-02-2023', '12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023', '16-02-2023', '17-02-2023', '18-02-2023', '19-02-2023', '20-02-2023', '21-02-2023', '22-02-2023', '23-02-2023', '24-02-2023', '25-02-2023', '26-02-2023', '27-02-2023', '28-02-2023', '01-03-2023']


In [32]:
## Q10. Given a dictionary, convert it into corresponding dataframe and display it
## dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
